/**
 * Acceptance Test Specification Generator
 *
 * Generates a human-readable markdown document for acceptance testing.
 * The document is designed to be filled in by a human tester who:
 * 1. Reads each test case
 * 2. Executes the steps manually (or with AI assistance)
 * 3. Records pass/fail/skip with notes
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import type { HardenTestCase } from "../../types";

export interface AcceptanceSpec {
  featureId: string;
  featureName: string;
  version: string;
  generatedAt: string;
  specHash: string;
  testCases: AcceptanceTestCase[];
}

export interface AcceptanceTestCase {
  id: string;
  title: string;
  requirement: string;
  priority: "critical" | "high" | "medium" | "low";
  preconditions: string[];
  steps: string[];
  expectedResult: string;
  // Result fields - filled in by human
  status?: "pass" | "fail" | "skip" | "pending";
  testedBy?: string;
  testedAt?: string;
  notes?: string;
}

/**
 * Generate acceptance test specification markdown
 */
export function generateAcceptanceSpec(
  featureId: string,
  featureName: string,
  testCases: HardenTestCase[],
  specHash: string
): string {
  const now = new Date().toISOString().split("T")[0];

  const lines: string[] = [
    `# Acceptance Test Specification`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Feature** | ${featureId} - ${featureName} |`,
    `| **Version** | 1.0 |`,
    `| **Generated** | ${now} |`,
    `| **Spec Hash** | ${specHash.slice(0, 8)} |`,
    ``,
    `## Summary`,
    ``,
    `| Total | Pass | Fail | Skip | Pending |`,
    `|-------|------|------|------|---------|`,
    `| ${testCases.length} | | | | ${testCases.length} |`,
    ``,
    `---`,
    ``,
  ];

  for (const tc of testCases) {
    lines.push(`## ${tc.id}: ${tc.description}`);
    lines.push(``);
    lines.push(`**Requirement:** ${tc.source}`);
    lines.push(`**Type:** ${tc.type}`);
    lines.push(``);

    if (tc.preconditions.length > 0) {
      lines.push(`### Preconditions`);
      for (const pre of tc.preconditions) {
        lines.push(`- ${pre}`);
      }
      lines.push(``);
    }

    lines.push(`### Test Steps`);
    for (let i = 0; i < tc.steps.length; i++) {
      lines.push(`${i + 1}. ${tc.steps[i]}`);
    }
    lines.push(``);

    lines.push(`### Expected Result`);
    lines.push(tc.expectedResult);
    lines.push(``);

    lines.push(`### Result`);
    lines.push(``);
    lines.push(`**Status:**`);
    lines.push(``);
    lines.push(`**Findings:**`);
    lines.push(``);
    lines.push(``);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  // Add footer with instructions
  lines.push(`## Instructions`);
  lines.push(``);
  lines.push(`For each test case:`);
  lines.push(`1. Read the steps and expected result`);
  lines.push(`2. Execute the test (manually or with AI assistance)`);
  lines.push(`3. Record **Status** as: \`pass\`, \`fail\`, or \`skip\``);
  lines.push(`4. Write your **Findings** - what you observed, any issues`);
  lines.push(``);
  lines.push(`Update the Summary table when complete.`);
  lines.push(``);
  lines.push(`---`);
  lines.push(`*Generated by SpecFlow*`);

  return lines.join("\n");
}

/**
 * Write acceptance spec to file
 */
export function writeAcceptanceSpec(
  projectPath: string,
  featureId: string,
  content: string
): string {
  const dir = join(projectPath, ".specify", "harden", featureId.toLowerCase());
  mkdirSync(dir, { recursive: true });

  const filePath = join(dir, "acceptance-test.md");
  writeFileSync(filePath, content);

  return filePath;
}

/**
 * Read existing acceptance spec if present
 */
export function readAcceptanceSpec(
  projectPath: string,
  featureId: string
): string | null {
  const filePath = join(projectPath, ".specify", "harden", featureId.toLowerCase(), "acceptance-test.md");
  if (!existsSync(filePath)) return null;
  return readFileSync(filePath, "utf-8");
}
