/**
 * Embedded Migrations
 *
 * AUTO-GENERATED by scripts/embed-migrations.ts
 * DO NOT EDIT MANUALLY
 *
 * Generated: 2026-02-02T06:47:26.460Z
 *
 * These migrations are embedded at build time so they work
 * in the compiled binary where import.meta.dir resolves to
 * a virtual path inside the binary.
 */

import type { Migration } from "./types";

/**
 * Embedded migrations for use when filesystem migrations are unavailable
 * (e.g., in compiled binary)
 */
export const EMBEDDED_MIGRATIONS: Migration[] = [
  {
    version: 1,
    name: "add_quick_start",
    upSql: `ALTER TABLE features ADD COLUMN quick_start INTEGER DEFAULT 0;`,
    downSql: `-- Note: SQLite doesn't support DROP COLUMN directly in older versions
-- This is a no-op for safety; manual intervention required for rollback
SELECT 1;`,
  },
  {
    version: 2,
    name: "add_doctorow_verified",
    upSql: `ALTER TABLE features ADD COLUMN doctorow_verified INTEGER DEFAULT 0;
ALTER TABLE features ADD COLUMN doctorow_skips TEXT;`,
    downSql: `SELECT 1;`,
  },
  {
    version: 3,
    name: "add_revision_history",
    upSql: `CREATE TABLE IF NOT EXISTS revision_history (
  id TEXT PRIMARY KEY,
  artifact_path TEXT NOT NULL,
  previous_content TEXT NOT NULL,
  timestamp TEXT NOT NULL,
  reason TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_revision_history_path ON revision_history(artifact_path);
CREATE INDEX IF NOT EXISTS idx_revision_history_timestamp ON revision_history(timestamp);`,
    downSql: `DROP INDEX IF EXISTS idx_revision_history_timestamp;
DROP INDEX IF EXISTS idx_revision_history_path;
DROP TABLE IF EXISTS revision_history;`,
  },
  {
    version: 4,
    name: "add_decomposition_fields",
    upSql: `-- Add rich decomposition fields for batch mode support
-- All columns nullable for backward compatibility with existing features

-- Required fields for batch mode
ALTER TABLE features ADD COLUMN problem_type TEXT;
ALTER TABLE features ADD COLUMN urgency TEXT;
ALTER TABLE features ADD COLUMN primary_user TEXT;
ALTER TABLE features ADD COLUMN integration_scope TEXT;

-- Optional rich fields
ALTER TABLE features ADD COLUMN usage_context TEXT;
ALTER TABLE features ADD COLUMN data_requirements TEXT;
ALTER TABLE features ADD COLUMN performance_requirements TEXT;
ALTER TABLE features ADD COLUMN priority_tradeoff TEXT;

-- Uncertainty handling
ALTER TABLE features ADD COLUMN uncertainties TEXT;
ALTER TABLE features ADD COLUMN clarification_needed TEXT;`,
    downSql: `-- Note: SQLite doesn't support DROP COLUMN directly in older versions
-- This is a no-op for safety; manual intervention required for rollback
SELECT 1;`,
  },
  {
    version: 5,
    name: "add_skip_validation",
    upSql: `-- Add skip validation and audit trail fields
-- Tracks why features were skipped and validates skip decisions

-- Skip audit trail
ALTER TABLE features ADD COLUMN skip_reason TEXT;
ALTER TABLE features ADD COLUMN skip_justification TEXT;
ALTER TABLE features ADD COLUMN skip_validated_at TEXT;
ALTER TABLE features ADD COLUMN skip_duplicate_of TEXT;`,
    downSql: `-- Note: SQLite doesn't support DROP COLUMN directly in older versions
-- This is a no-op for safety; manual intervention required for rollback
SELECT 1;`,
  },
  {
    version: 6,
    name: "add_contrib_prep",
    upSql: `-- Add contrib prep state tracking table
-- Tracks the contribution preparation workflow (inventory → sanitize → extract → verify)

CREATE TABLE IF NOT EXISTS contrib_prep_state (
  feature_id TEXT PRIMARY KEY,
  gate INTEGER NOT NULL DEFAULT 0,
  inventory_included INTEGER DEFAULT 0,
  inventory_excluded INTEGER DEFAULT 0,
  sanitization_pass INTEGER,
  sanitization_findings INTEGER DEFAULT 0,
  tag_name TEXT,
  tag_hash TEXT,
  contrib_branch TEXT,
  verification_pass INTEGER,
  base_branch TEXT DEFAULT 'main',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (feature_id) REFERENCES features(id)
);`,
    downSql: `DROP TABLE IF EXISTS contrib_prep_state;`,
  },
  {
    version: 7,
    name: "add_spec_deltas",
    upSql: `-- Add spec versioning and delta tracking tables
-- Tracks specification evolution across versions with ADDED/MODIFIED/REMOVED change types

CREATE TABLE IF NOT EXISTS spec_versions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feature_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  FOREIGN KEY (feature_id) REFERENCES features(id),
  UNIQUE(feature_id, version)
);

CREATE TABLE IF NOT EXISTS spec_deltas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feature_id TEXT NOT NULL,
  from_version INTEGER NOT NULL,
  to_version INTEGER NOT NULL,
  change_type TEXT NOT NULL CHECK(change_type IN ('ADDED', 'MODIFIED', 'REMOVED')),
  section_path TEXT NOT NULL,
  diff_content TEXT,
  FOREIGN KEY (feature_id) REFERENCES features(id)
);

CREATE INDEX IF NOT EXISTS idx_spec_versions_feature_id ON spec_versions(feature_id);
CREATE INDEX IF NOT EXISTS idx_spec_deltas_lookup ON spec_deltas(feature_id, from_version, to_version);`,
    downSql: `DROP INDEX IF EXISTS idx_spec_deltas_lookup;
DROP INDEX IF EXISTS idx_spec_versions_feature_id;
DROP TABLE IF EXISTS spec_deltas;
DROP TABLE IF EXISTS spec_versions;`,
  },
  {
    version: 8,
    name: "approval_gates",
    upSql: `CREATE TABLE IF NOT EXISTS approval_gates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    feature_id TEXT NOT NULL,
    phase_boundary TEXT NOT NULL,
    urgency TEXT NOT NULL CHECK (urgency IN ('critical', 'review', 'ambient')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'auto_approved', 'timed_out')),
    triggered_at TEXT NOT NULL,
    resolved_at TEXT,
    timeout_at TEXT,
    resolved_by TEXT,
    rejection_reason TEXT,
    FOREIGN KEY (feature_id) REFERENCES features(id)
);

CREATE INDEX idx_approval_gates_pending ON approval_gates(status) WHERE status = 'pending';
CREATE INDEX idx_approval_gates_feature ON approval_gates(feature_id);`,
    downSql: `DROP INDEX IF EXISTS idx_approval_gates_feature;
DROP INDEX IF EXISTS idx_approval_gates_pending;
DROP TABLE IF EXISTS approval_gates;`,
  },
  {
    version: 9,
    name: "pipeline_failures",
    upSql: `CREATE TABLE IF NOT EXISTS pipeline_failures (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    feature_id TEXT NOT NULL,
    phase TEXT NOT NULL,
    missing_artifacts TEXT NOT NULL,
    error_message TEXT,
    last_successful_phase TEXT,
    resume_count INTEGER NOT NULL DEFAULT 0,
    blocked_at TEXT NOT NULL,
    resolved_at TEXT,
    FOREIGN KEY (feature_id) REFERENCES features(id)
);

CREATE INDEX idx_pipeline_failures_feature ON pipeline_failures(feature_id);
CREATE INDEX idx_pipeline_failures_unresolved ON pipeline_failures(resolved_at) WHERE resolved_at IS NULL;`,
    downSql: `DROP INDEX IF EXISTS idx_pipeline_failures_unresolved;
DROP INDEX IF EXISTS idx_pipeline_failures_feature;
DROP TABLE IF EXISTS pipeline_failures;`,
  },
  {
    version: 10,
    name: "add_execution_log",
    upSql: `CREATE TABLE IF NOT EXISTS execution_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    feature_id TEXT NOT NULL,
    phase TEXT NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    duration_seconds INTEGER,
    status TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed', 'skipped', 'blocked')),
    git_sha_before TEXT,
    git_sha_after TEXT,
    artifacts_produced TEXT,
    error_message TEXT,
    FOREIGN KEY (feature_id) REFERENCES features(id)
);

CREATE INDEX idx_execution_log_feature ON execution_log(feature_id);
CREATE INDEX idx_execution_log_feature_phase ON execution_log(feature_id, phase);`,
    downSql: `DROP INDEX IF EXISTS idx_execution_log_feature_phase;
DROP INDEX IF EXISTS idx_execution_log_feature;
DROP TABLE IF EXISTS execution_log;`,
  },
  {
    version: 11,
    name: "add_evolve_fields",
    upSql: `ALTER TABLE features ADD COLUMN evolved_at TEXT;
ALTER TABLE features ADD COLUMN baseline_path TEXT;`,
    downSql: `SELECT 1;`,
  },
  {
    version: 12,
    name: "harden_sessions",
    upSql: `CREATE TABLE IF NOT EXISTS harden_sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feature_id TEXT NOT NULL,
  started_at TEXT NOT NULL,
  completed_at TEXT,
  result TEXT NOT NULL DEFAULT 'incomplete'
    CHECK (result IN ('pass', 'fail', 'incomplete')),
  total_tests INTEGER NOT NULL DEFAULT 0,
  passed INTEGER NOT NULL DEFAULT 0,
  failed INTEGER NOT NULL DEFAULT 0,
  skipped INTEGER NOT NULL DEFAULT 0,
  protocol_path TEXT NOT NULL,
  report_path TEXT,
  FOREIGN KEY (feature_id) REFERENCES features(id)
);
CREATE INDEX idx_harden_sessions_feature ON harden_sessions(feature_id);

CREATE TABLE IF NOT EXISTS harden_test_cases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id INTEGER NOT NULL,
  test_id TEXT NOT NULL,
  description TEXT NOT NULL,
  source TEXT NOT NULL,
  test_type TEXT NOT NULL DEFAULT 'manual'
    CHECK (test_type IN ('automated', 'manual', 'hybrid')),
  preconditions TEXT,
  steps TEXT NOT NULL,
  expected_result TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'pass', 'fail', 'skipped')),
  notes TEXT,
  executed_at TEXT,
  FOREIGN KEY (session_id) REFERENCES harden_sessions(id)
);
CREATE INDEX idx_harden_test_cases_session ON harden_test_cases(session_id);`,
    downSql: `DROP INDEX IF EXISTS idx_harden_test_cases_session;
DROP INDEX IF EXISTS idx_harden_sessions_feature;
DROP TABLE IF EXISTS harden_test_cases;
DROP TABLE IF EXISTS harden_sessions;`,
  },
];
